/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * SHDLC-Generator: 0.8.2
 * Yaml Version: 0.1.0
 * Template Version: 0.7.0
 */
/*
 * Copyright (c) 2021, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "sen44_uart.h"
#include "sensirion_common.h"
#include "sensirion_shdlc.h"
#include "sensirion_test_setup.h"
#include "sensirion_uart_hal.h"
#include <inttypes.h>
#include <stdio.h>

TEST_GROUP (SEN44_Tests) {
    void setup() {
        int16_t error;
        error = sensirion_uart_hal_init();
        // TODO: DRIVER_GENERATOR Adjust UART port as soon as LKD-364 is done
        CHECK_EQUAL_ZERO_TEXT(error, "sensirion_uart_hal_init");
    }

    void teardown() {
        int16_t error;

        error = sen44_device_reset();
        CHECK_EQUAL_ZERO_TEXT(error, "sen44_device_reset");

        error = sensirion_uart_hal_free();
        CHECK_EQUAL_ZERO_TEXT(error, "sensirion_uart_hal_free");
    }
};

TEST (SEN44_Tests, SEN44_Test_start_measurement) {
    int16_t error;
    error = sen44_start_measurement();
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_start_measurement");

    error = sen44_start_measurement();
    CHECK_EQUAL_TEXT(error, SENSIRION_SHDLC_ERR_EXECUTION_FAILURE,
                     "repeated start should fail");
}

TEST (SEN44_Tests, SEN44_Test_stop_measurement) {
    int16_t error;
    error = sen44_stop_measurement();
    CHECK_EQUAL_TEXT(error, SENSIRION_SHDLC_ERR_EXECUTION_FAILURE,
                     "stop measurement after reset should fail");

    error = sen44_start_measurement();
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_start_measurement");

    error = sen44_stop_measurement();
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_stop_measurement");
}

TEST (SEN44_Tests, SEN44_Test_read_data_ready) {
    int16_t error;
    bool data_ready;
    error = sen44_read_data_ready(&data_ready);
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_read_data_ready");
    CHECK_EQUAL_TEXT(data_ready, false,
                     "data ready should be false after reset");

    error = sen44_start_measurement();
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_start_measurement");

    sensirion_uart_hal_sleep_usec(1100000);

    error = sen44_read_data_ready(&data_ready);
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_read_data_ready");
    CHECK_EQUAL_TEXT(data_ready, true,
                     "data ready should be true after measurement");
}

TEST (SEN44_Tests, SEN44_Test_read_measured_pm_values) {
    int16_t error;
    uint16_t mass_concentration_pm1p0;
    uint16_t mass_concentration_pm2p5;
    uint16_t mass_concentration_pm4p0;
    uint16_t mass_concentration_pm10p0;
    uint16_t number_concentration_pm0p5;
    uint16_t number_concentration_pm1p0;
    uint16_t number_concentration_pm2p5;
    uint16_t number_concentration_pm4p0;
    uint16_t number_concentration_pm10p0;
    uint16_t typical_particle_size;
    error = sen44_read_measured_pm_values(
        &mass_concentration_pm1p0, &mass_concentration_pm2p5,
        &mass_concentration_pm4p0, &mass_concentration_pm10p0,
        &number_concentration_pm0p5, &number_concentration_pm1p0,
        &number_concentration_pm2p5, &number_concentration_pm4p0,
        &number_concentration_pm10p0, &typical_particle_size);
    CHECK_EQUAL_TEXT(error, SENSIRION_SHDLC_ERR_EXECUTION_FAILURE,
                     "read measurement after reset should fail");

    error = sen44_start_measurement();
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_start_measurement");

    sensirion_uart_hal_sleep_usec(1100000);

    error = sen44_read_measured_pm_values(
        &mass_concentration_pm1p0, &mass_concentration_pm2p5,
        &mass_concentration_pm4p0, &mass_concentration_pm10p0,
        &number_concentration_pm0p5, &number_concentration_pm1p0,
        &number_concentration_pm2p5, &number_concentration_pm4p0,
        &number_concentration_pm10p0, &typical_particle_size);
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_read_measured_pm_values");
    printf("Mass concentration pm1p0: %u\n", mass_concentration_pm1p0);
    printf("Mass concentration pm2p5: %u\n", mass_concentration_pm2p5);
    printf("Mass concentration pm4p0: %u\n", mass_concentration_pm4p0);
    printf("Mass concentration pm10p0: %u\n", mass_concentration_pm10p0);
    printf("Number concentration pm0p5: %u\n", number_concentration_pm0p5);
    printf("Number concentration pm1p0: %u\n", number_concentration_pm1p0);
    printf("Number concentration pm2p5: %u\n", number_concentration_pm2p5);
    printf("Number concentration pm4p0: %u\n", number_concentration_pm4p0);
    printf("Number concentration pm10p0: %u\n", number_concentration_pm10p0);
    printf("Typical particle size: %u\n", typical_particle_size);
}

TEST (SEN44_Tests,
      SEN44_Test_read_measured_mass_concentration_and_ambient_values) {
    int16_t error;
    uint16_t mass_concentration_pm1p0;
    uint16_t mass_concentration_pm2p5;
    uint16_t mass_concentration_pm4p0;
    uint16_t mass_concentration_pm10p0;
    int16_t voc_index;
    int16_t ambient_humidity;
    int16_t ambient_temperature;
    error = sen44_read_measured_mass_concentration_and_ambient_values(
        &mass_concentration_pm1p0, &mass_concentration_pm2p5,
        &mass_concentration_pm4p0, &mass_concentration_pm10p0, &voc_index,
        &ambient_humidity, &ambient_temperature);
    CHECK_EQUAL_TEXT(error, SENSIRION_SHDLC_ERR_EXECUTION_FAILURE,
                     "read measurement after reset should fail");

    error = sen44_start_measurement();
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_start_measurement");

    sensirion_uart_hal_sleep_usec(1100000);

    error = sen44_read_measured_mass_concentration_and_ambient_values(
        &mass_concentration_pm1p0, &mass_concentration_pm2p5,
        &mass_concentration_pm4p0, &mass_concentration_pm10p0, &voc_index,
        &ambient_humidity, &ambient_temperature);
    CHECK_EQUAL_ZERO_TEXT(
        error, "sen44_read_measured_mass_concentration_and_ambient_values");
    printf("Mass concentration pm1p0: %u\n", mass_concentration_pm1p0);
    printf("Mass concentration pm2p5: %u\n", mass_concentration_pm2p5);
    printf("Mass concentration pm4p0: %u\n", mass_concentration_pm4p0);
    printf("Mass concentration pm10p0: %u\n", mass_concentration_pm10p0);
    printf("Voc index: %i\n", voc_index);
    printf("Ambient humidity: %i\n", ambient_humidity);
    printf("Ambient temperature: %i\n", ambient_temperature);
}

TEST (SEN44_Tests, SEN44_Test_read_measured_ambient_values) {
    int16_t error;
    int16_t voc_index;
    int16_t ambient_humidity;
    int16_t ambient_temperature;
    error = sen44_read_measured_ambient_values(&voc_index, &ambient_humidity,
                                               &ambient_temperature);
    CHECK_EQUAL_TEXT(error, SENSIRION_SHDLC_ERR_EXECUTION_FAILURE,
                     "read measurement after reset should fail");

    error = sen44_start_measurement();
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_start_measurement");

    sensirion_uart_hal_sleep_usec(1100000);

    error = sen44_read_measured_ambient_values(&voc_index, &ambient_humidity,
                                               &ambient_temperature);
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_read_measured_ambient_values");
    printf("Voc index: %i\n", voc_index);
    printf("Ambient humidity: %i\n", ambient_humidity);
    printf("Ambient temperature: %i\n", ambient_temperature);
}

TEST (SEN44_Tests, SEN44_Test_start_fan_cleaning) {
    int16_t error;
    error = sen44_start_fan_cleaning();
    CHECK_EQUAL_TEXT(error, SENSIRION_SHDLC_ERR_EXECUTION_FAILURE,
                     "start fan cleaning after reset should fail");

    error = sen44_start_measurement();
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_start_measurement");

    error = sen44_start_fan_cleaning();
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_start_fan_cleaning");
}

TEST (SEN44_Tests, SEN44_Test_set_auto_cleaning_interval) {
    int16_t error;
    uint32_t interval = 0;
    error = sen44_set_auto_cleaning_interval(interval);
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_set_auto_cleaning_interval");
}

TEST (SEN44_Tests, SEN44_Test_get_auto_cleaning_interval) {
    int16_t error;
    uint32_t interval;
    error = sen44_get_auto_cleaning_interval(&interval);
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_get_auto_cleaning_interval");
    printf("interval: %u\n", interval);
}

TEST (SEN44_Tests, SEN44_Test_get_article_code) {
    int16_t error;
    unsigned char article_code[42];
    uint8_t article_code_size = 42;
    error = sen44_get_article_code(&article_code[0], article_code_size);
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_get_article_code");
    printf("Article code: %s\n", article_code);
}

TEST (SEN44_Tests, SEN44_Test_get_serial_number) {
    int16_t error;
    unsigned char serial_number[42];
    uint8_t serial_number_size = 42;
    error = sen44_get_serial_number(&serial_number[0], serial_number_size);
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_get_serial_number");
    printf("Serial number: %s\n", serial_number);
}

TEST (SEN44_Tests, SEN44_Test_get_version) {
    int16_t error;
    uint8_t firmware_major;
    uint8_t firmware_minor;
    bool firmware_debug;
    uint8_t hardware_major;
    uint8_t hardware_minor;
    uint8_t protocol_major;
    uint8_t protocol_minor;
    error = sen44_get_version(&firmware_major, &firmware_minor, &firmware_debug,
                              &hardware_major, &hardware_minor, &protocol_major,
                              &protocol_minor);
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_get_version");
    printf("Firmware: %u.%u\n", firmware_major, firmware_minor);
    printf("Firmware debug: %s\n", firmware_debug ? "true" : "false");
    printf("Hardware: %u.%u\n", hardware_major, hardware_minor);
    printf("Protocol: %u.%u\n", protocol_major, protocol_minor);
}

TEST (SEN44_Tests, SEN44_Test_read_device_status) {
    int16_t error;
    bool clear = 0;
    uint32_t device_status;
    uint8_t last_error;
    error = sen44_read_device_status(clear, &device_status, &last_error);
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_read_device_status");
    printf("device_status: %u\n", device_status);
    printf("last_error: %u\n", last_error);
}

TEST (SEN44_Tests, SEN44_Test_device_reset) {
    int16_t error;
    error = sen44_device_reset();
    CHECK_EQUAL_ZERO_TEXT(error, "sen44_device_reset");
}
